### PR TITLE
Add SASS/SCSS support

### LINKED ISSUE #3: SASS Support
Use https://github.com/sass/node-sass

### PR DESCRIPTION
**Pull request by nemoDreamer**
Using `node-sass`.

Closes #3.

### CODE REVIEW

**Comment by Glavin001** [comment]
@nemoDreamer this project is no longer maintained, or used, by me.

If you are interested in contributing, I could give you access to this repo so you can merge pull Requests (3 currently open, including this one) and publish updates. What do you think? 😃

**Comment by nemoDreamer** [comment]
Oh that's a shame, @Glavin001 ...! From what I've played around with, this is one of the most efficient preview packages out there 😢 . The alternatives are either clunky or steal focus to the preview window with every edit...

If you want to give me access, that's great. I'll look into those other pending pull requests to see whether I'm qualified to review them.

**Comment by Glavin001** [comment]
@nemoDreamer I've invited you to be a collaborator of this repository.

> From what I've played around with, this is one of the most efficient preview packages out there 

🎉 Glad to hear it! Thanks!

**Comment by nemoDreamer** [comment]
I've been using this in dev mode for the last 3 days and have ironed out the kinks: I think it's ready. Gonna merge and publish!

**Comment by nemoDreamer** [comment]
Doh... Jumped to v0.19 because first publish failed and I forgot to reset `HEAD` to before `Prepare 0.18.0 release`. Sorry for that... 😢

**Pull request merged**
