### PR TITLE
Added CJSX support

### PR DESCRIPTION
**Pull request by ScreenDriver**
See also #96

### CODE REVIEW

**Comment by Glavin001** [comment]
I need to add an example file for this.

How about:

```coffee
Car = React.createClass
  render: ->
    <Vehicle doors={4} locked={isLocked()} data-colour="red" on>
      <Parts.FrontSeat />
      <Parts.BackSeat />
      <p className="seat">Which seat can I take? {@props?.seat or 'none'}</p>
      {# also, this is a comment }
    </Vehicle>
```

**Comment by ScreenDriver** [comment]
Looks good :+1:

**Comment by Glavin001** [comment]
Published to v.0.16.0

**Comment by ScreenDriver** [comment]
Thank you. Updated and it's working :relaxed:

**Pull request merged**
