### PR TITLE
Added babel experimental support

### LINKED ISSUE #114: Babel experimental support
Preview fails if you use one of the [experimental](http://babeljs.io/docs/usage/experimental/) features.

### PR DESCRIPTION
**Pull request by screendriver**
Fixes #114

### CODE REVIEW

**Comment by screendriver** [comment]
I also deleted `JavaScript (JSX)` and `react-tools` dependency because it's deprecated and natively supported in Babel since some months.

**Comment by Glavin001** [comment]
Excellent. Thank you for contributing!

**Comment by Glavin001** [comment]
Published to v0.16.6

**Comment by screendriver** [comment]
:+1:

**Pull request merged**
